const MODEL_PATHS = Object.freeze([
    { id: 'One Pancras Square', file: require('../../assets/models/1PancrasSquare.glb') },
    { id: 'Television Centre', file: require('../../assets/models/TelevisionCentre.glb') },
    { id: '30 St Mary\'s Axe', file: require('../../assets/models/30StMarysAxe.glb') },
    { id: 'Lloyds Of London', file: require('../../assets/models/LloydsOfLondonSite.glb') },
    { id: 'Lloyds Of London Metals', file: require('../../assets/models/LloydsOfLondonMetalsSite.glb') },
    { id: '20 Fenchurch Street', file: require('../../assets/models/20FenchurchStreetSite.glb') },
    { id: '10 Portman Square', file: require('../../assets/models/10PortmanSquare.glb') },
    { id: 'Marble Arch House', file: require('../../assets/models/MarbleArchHouse.glb') },
    { id: 'York House', file: require('../../assets/models/YorkHouse.glb') },
    { id: '201 Bishopsgate', file: require('../../assets/models/201Bishopsgate.glb') },
    { id: '2 London Wall', file: require('../../assets/models/2LondonWall.glb') },
    { id: '99 Bishopsgate', file: require('../../assets/models/99Bishopsgate.glb') },
    { id: 'The Shard', file: require('../../assets/models/TheShardSite.glb') },
    { id: 'Dashwood', file: require('../../assets/models/Dashwood.glb') },
    { id: '22 Bishopsgate', file: require('../../assets/models/22Bishopsgate.glb') },
    { id: '3 Sheldon Square', file: require('../../assets/models/3SheldonSquare.glb') },
    { id: '4 Kingdom Street', file: require('../../assets/models/4KingdomStreet.glb') },
    { id: 'Ropemaker', file: require('../../assets/models/Ropemaker.glb') },
    { id: '2 Kingdom Street', file: require('../../assets/models/2KingdomStreet.glb') },
    { id: '6 More London', file: require('../../assets/models/6MoreLondonSite.glb') },
    { id: 'The Crick', file: require('../../assets/models/TheCrick.glb') },
    { id: '199 Bishopsgate', file: require('../../assets/models/199Bishopsgate.glb') },
    { id: '110 Bishopsgate', file: require('../../assets/models/110Bishopsgate.glb') },
    { id: '1 Appold Street', file: require('../../assets/models/1AppoldStreet.glb') },
    { id: 'Exchange House', file: require('../../assets/models/ExchangeHouse.glb') },
    { id: 'Exchange Square', file: require('../../assets/models/ExchangeSquare.glb') },
    { id: 'Broadwalk', file: require('../../assets/models/Broadwalk.glb') },
    { id: 'Broadgate Tower', file: require('../../assets/models/BroadgateTower.glb') },
    { id: '1 Finsbury Avenue', file: require('../../assets/models/1FinsburyAvenue.glb') },
    { id: '135 Bishopsgate', file: require('../../assets/models/135Bishopsgate.glb') },
    { id: '155 Bishopsgate', file: require('../../assets/models/155Bishopsgate.glb') },
    { id: '100 Liverpool Street', file: require('../../assets/models/100LiverpoolStreet.glb') },
    { id: 'One New Change', file: require('../../assets/models/OneNewChangeSite.glb') },
    { id: '30 North Colonnade', file: require('../../assets/models/30NorthColonnade.glb') },
    { id: 'Fish Coal', file: require('../../assets/models/FishCoal.glb') },
    { id: 'K3', file: require('../../assets/models/K3MidlandsGoodShed.glb') },
    { id: 'R7', file: require('../../assets/models/R7Handyside.glb') },
    { id: 'Q1 Handyside', file: require('../../assets/models/Q1Handyside.glb') },
    { id: 'Western Transit', file: require('../../assets/models/WesternTransitShed.glb') },
    { id: 'Two Pancras Square', file: require('../../assets/models/2PancrasSquare.glb') },
    { id: 'Three Pancras Square', file: require('../../assets/models/3PancrasSquare.glb') },
    { id: 'Four Pancras Square', file: require('../../assets/models/4PancrasSquare.glb') },
    { id: '11 - 21 Canal Reach', file: require('../../assets/models/11-21CanalReach.glb') },
    { id: 'Coal Drops Yard', file: require('../../assets/models/CoalDropsYard.glb') },
    { id: 'Cannon Place', file: require('../../assets/models/CannonPlace.glb') },
    { id: 'Bluefin', file: require('../../assets/models/Bluefin.glb') },
    { id: '10 Cubitt Square', file: require('../../assets/models/10CubittSquare.glb') },
    { id: 'Wellcome Trust', file: require('../../assets/models/WellcomeTrust.glb') },
    { id: 'Walt Disney', file: require('../../assets/models/WaltDisney.glb') },
    { id: 'Bloom Clenkerwell', file: require('../../assets/models/BloomClerkenwell.glb') },
    { id: '1 London Bridge', file: require('../../assets/models/1LondonBridgeSite.glb') },
    { id: '1 Sheldon Square', file: require('../../assets/models/1SheldonSquare.glb') },
    { id: '2 More London', file: require('../../assets/models/2MoreLondonSite.glb') },
    { id: 'Aldgate Tower', file: require('../../assets/models/AldgateTower.glb') },
    { id: 'CityPoint', file: require('../../assets/models/CityPoint.glb') },
    { id: 'Cottons  Centre', file: require('../../assets/models/CottonsCentreSite.glb') },
    { id: 'Hays\s Galleria', file: require('../../assets/models/HaysGalleriaSite.glb') },
    { id: 'Islington Square', file: require('../../assets/models/IslingtonSquare.glb') },
    { id: 'Kings Place', file: require('../../assets/models/KingsPlace.glb') },
    { id: 'S1-Handyside', file: require('../../assets/models/S1Handyside.glb') },
    { id: 'S2 Handyside', file: require('../../assets/models/S2Handyside.glb') },
    { id: '183 Euston Road', file: require('../../assets/models/183EustonRoad.glb') },
])

export const getModelPathFromId = (id) => {
    const modelIndex = MODEL_PATHS.findIndex(model => model.id === id)
    if (modelIndex < 0) {
        return require('../../assets/models/defaultModel.glb')
    }
    return MODEL_PATHS[modelIndex].file
}